const PROFILES=['Raquel','Sara','Carmen Hernandez','Lucía','Carmen gago','Nuria','Rebeca','Marta'];
const COLORS=['rojo','azul','verde','amarillo','morado','rosa','naranja','turquesa'];
const R=['croquetas','cerveza','chiva','vater','cruz'];
const LABEL={croquetas:'Croquetas',cerveza:'Cerveza',chiva:'Chiva',vater:'Váter',cruz:'Cruz religiosa de madera'};
const ICON={croquetas:'assets/cards/croquetas.svg',cerveza:'assets/cards/cerveza.svg',chiva:'assets/cards/chiva.svg',vater:'assets/cards/vater.svg',cruz:'assets/cards/cruz.svg'};
const DEV={caballero:['El perseguidor','assets/cards/caballero.svg'],punto:['Punto secreto','assets/cards/punto.svg'],monopolio:['Aquí mando yo','assets/cards/monopolio.svg'],abundancia:['Dos por el precio de ninguno','assets/cards/abundancia.svg'],construccion:['Obra y gracia','assets/cards/construccion.svg']};
const PIECES={Raquel:['assets/pieces/Raquel/keyboard.svg','assets/pieces/Raquel/padel.svg','assets/pieces/Raquel/igloo.svg'],Sara:['assets/pieces/Sara/pills.svg','assets/pieces/Sara/controller.svg','assets/pieces/Sara/stable.svg'],'Carmen Hernandez':['assets/pieces/Carmen-Hernandez/cigarette.svg','assets/pieces/Carmen-Hernandez/stadium.svg','assets/pieces/Carmen-Hernandez/falla.svg'],Lucía:['assets/pieces/Lucía/trail.svg','assets/pieces/Lucía/tent.svg','assets/pieces/Lucía/hospital.svg'],'Carmen gago':['assets/pieces/Carmen-gago/poop.svg','assets/pieces/Carmen-gago/bridge.svg','assets/pieces/Carmen-gago/metro.svg'],Nuria:['assets/pieces/Nuria/police-baton.svg','assets/pieces/Nuria/station.svg','assets/pieces/Nuria/jail.svg'],Rebeca:['assets/pieces/Rebeca/vape.svg','assets/pieces/Rebeca/cows.svg','assets/pieces/Rebeca/castle.svg'],Marta:['assets/pieces/Marta/sunglasses.svg','assets/pieces/Marta/gate.svg','assets/pieces/Marta/techno.svg']};
const FACE=['😎','🤪','😂','😈','🤠','🤓','🥳','😏'];
let ws=null,myId=null,state=null,profile=null; let buildMode=null;
const app=document.getElementById('app');
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const send=o=>{if(ws?.readyState===1)ws.send(JSON.stringify(o))};
function toast(t){const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.append(e);setTimeout(()=>e.remove(),2300)}
function beep(type='ok'){if(localStorage.getItem('catan_sound')==='off')return;try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.type='sine';o.frequency.value=type==='dice'?360:type==='win'?720:520;g.gain.value=.045;o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+(type==='win'?.45:.12));}catch{}}
function connect(action){if(ws){try{ws.close()}catch{}}ws=new WebSocket(location.origin.replace(/^http/,'ws'));ws.onopen=()=>send(action);ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='hello'){myId=m.id;localStorage.setItem('catan_lastCode',m.code)}else if(m.type==='state'){state=m.state;render(); if(state.turn===myId&&state.phase==='playing'&&!state.rolled)beep('ok')}else if(m.type==='err'){toast(m.msg);beep('bad')}};ws.onclose=()=>toast('Conexión perdida. Si vuelves a abrir la misma partida, el estado del servidor se conserva mientras siga activa.')}
function saved(p){try{return JSON.parse(localStorage.getItem('catan_profile_'+p)||'{}')}catch{return{}}}
function home(){app.innerHTML=`<div class="home"><div class="hero"><div class="logo">CATAN <span>GG</span></div><p>Tu Catan absurdo, personalizado y privado.</p></div><div class="profileGrid">${PROFILES.map((p,i)=>{const s=saved(p);return `<button class="profileCard" onclick="choose('${p}')"><div class="face">${s.photo?`<img src="${esc(s.photo)}">`:FACE[i]}</div><b>${esc(s.name||p)}</b><small>${p}</small></button>`}).join('')}</div><div class="tiny">2–8 jugadoras · sin cuentas · sin chat integrado · solo efectos de juego</div></div>`}
window.choose=p=>{profile=p;const s=saved(p);app.innerHTML=`<div class="center"><div class="panel narrow"><h1>${esc(p)}</h1><div class="avatarEdit">${s.photo?`<img id="preview" src="${esc(s.photo)}">`:`<div id="preview" class="face big">${FACE[PROFILES.indexOf(p)]}</div>`}<label class="upload">Cambiar foto<input id="photo" type="file" accept="image/*" onchange="photoPreview(event)"></label></div><label>Nombre<input id="name" maxlength="24" value="${esc(s.name||p)}"></label><label>Color<select id="color">${COLORS.map(c=>`<option ${s.color===c?'selected':''}>${c}</option>`).join('')}</select></label><div class="actions"><button onclick="createRoom()">Crear partida</button><button onclick="joinScreen()">Unirse a partida</button><button class="ghost" onclick="home()">Volver</button></div></div></div>`};
window.photoPreview=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{document.getElementById('preview').outerHTML=`<img id="preview" class="face big" src="${r.result}">`;window._photo=r.result};r.readAsDataURL(f)};
function saveProfile(){const o={name:document.getElementById('name').value.trim()||profile,color:document.getElementById('color').value,photo:window._photo||saved(profile).photo||''};localStorage.setItem('catan_profile_'+profile,JSON.stringify(o));return o}
window.createRoom=()=>{const s=saveProfile();connect({type:'create',profile,name:s.name,color:s.color,photo:s.photo})};
window.editConnectedProfile=()=>{const p=state.players[myId];window._photo=p.photo||'';app.innerHTML=`<div class="center"><div class="panel narrow"><h1>Modificar perfil</h1><div class="avatarEdit">${p.photo?`<img id="preview" class="face big" src="${esc(p.photo)}">`:`<div id="preview" class="face big">${FACE[PROFILES.indexOf(p.profile)]}</div>`}<label class="upload">Cambiar foto<input id="photo" type="file" accept="image/*" onchange="photoPreview(event)"></label></div><label>Nombre<input id="name" maxlength="24" value="${esc(p.name)}"></label><label>Color<select id="color">${COLORS.map(c=>`<option ${p.color===c?'selected':''}>${c}</option>`).join('')}</select></label><div class="actions"><button onclick="saveConnectedProfile()">Guardar cambios</button><button class="ghost" onclick="render()">Cancelar</button></div><p class="tiny">Los cambios se enviarán a todas las jugadoras inmediatamente.</p></div></div>`};
window.saveConnectedProfile=()=>{const name=document.getElementById('name').value.trim()||profile;const color=document.getElementById('color').value;const photo=window._photo||state.players[myId].photo||'';localStorage.setItem('catan_profile_'+profile,JSON.stringify({name,color,photo}));send({type:'profileUpdate',name,color,photo});};
window.joinScreen=()=>{const s=saved(profile);app.innerHTML=`<div class="center"><div class="panel narrow"><h1>Unirse</h1><label>Código de partida<input id="code" maxlength="5" value="${esc(localStorage.getItem('catan_lastCode')||'')}" style="text-transform:uppercase"></label><label>Nombre<input id="name" maxlength="24" value="${esc(s.name||profile)}"></label><label>Color<select id="color">${COLORS.map(c=>`<option ${s.color===c?'selected':''}>${c}</option>`).join('')}</select></label><div class="actions"><button onclick="joinRoom()">Entrar</button><button class="ghost" onclick="choose(profile)">Volver</button></div></div></div>`};
window.joinRoom=()=>{const s={name:document.getElementById('name').value.trim()||profile,color:document.getElementById('color').value,photo:saved(profile).photo||''};localStorage.setItem('catan_profile_'+profile,JSON.stringify(s));connect({type:'join',code:document.getElementById('code').value.toUpperCase(),profile,name:s.name,color:s.color,photo:s.photo})};
function lobby(){const ps=Object.entries(state.players);app.innerHTML=`<div class="center"><div class="panel lobby"><div class="logo smallLogo">CATAN <span>GG</span></div><h2>Sala <code>${state.code}</code></h2><p>Comparte este código con tus amigas.</p><div class="lobbyPlayers">${ps.map(([id,p])=>`<div class="lobbyP"><div class="avatar">${p.photo?`<img src="${p.photo}">`:'🙂'}</div><div><b>${esc(p.name)}</b><small>${p.profile}</small></div><i class="dot ${p.color}"></i>${id===state.host?'<span>👑</span>':''}${p.connected?'':'<span>⚪</span>'}</div>`).join('')}</div><div class="lobbyFoot"><b>${ps.filter(([,p])=>p.connected).length}/8 conectadas</b>${state.host===myId?`<button onclick="startGame()" ${ps.filter(([,p])=>p.connected).length<2?'disabled':''}>Empezar partida</button>`:'<span>La anfitriona inicia cuando estéis listas.</span>'}<button class="ghost" onclick="editConnectedProfile()">Modificar perfil</button><button class="ghost" onclick="leave()">Salir</button></div></div></div>`}
window.startGame=()=>send({type:'start'});window.leave=()=>{send({type:'leave'});setTimeout(home,100)};
function legalEdge(eid){
 const b=state.board,p=state.players[myId],e=b.edges[eid]; if(!e||p.roadsOn.includes(eid)) return false;
 if(p.roads<=0 && !(p.freeRoads>0)) return false;
 if(state.phase==='placement1'||state.phase==='placement2'){const last=p.settlementsOn[p.settlementsOn.length-1];return last!=null&&(e.a===last||e.b===last);}
 if(buildMode!=='road') return false;
 if(!(p.freeRoads>0) && !canPayClient({croquetas:1,cerveza:1})) return false;
 for(const v of [e.a,e.b]){
   const vv=b.vertices[v]; if(vv.owner===p.profile) return true;
   if(vv.owner) continue;
   if(p.roadsOn.some(x=>{const re=b.edges[x];return re.a===v||re.b===v})) return true;
 }
 return false;
}
function legalVertex(vid,kind){
 const b=state.board,p=state.players[myId],v=b.vertices[vid]; if(!v) return false;
 if(state.phase==='placement1'||state.phase==='placement2'){if(v.owner||v.adj.some(n=>b.vertices[n].owner))return false;return true;}
 if(kind==='city') return p.cities>0 && p.settlementsOn.includes(vid);
 if(kind!=='settlement') return false;
 if(p.settlements<=0) return false;
 if(v.owner) return false;
 if(v.adj.some(n=>b.vertices[n].owner)) return false;
 return v.adj.some(n=>p.roadsOn.some(eid=>{const e=b.edges[eid];return e.a===n||e.b===n}));
}
function canPayClient(c){const p=state.players[myId];return Object.entries(c).every(([r,n])=>p.res[r]>=n)}
function terrainImage(t){return t==='desierto'?'assets/terrain/desierto.svg':`assets/terrain/${t}.svg`}
function imgPiece(src,x,y,w,h,cls=''){return `<image class="pieceImg ${cls}" href="${src}" x="${x-w/2}" y="${y-h/2}" width="${w}" height="${h}" preserveAspectRatio="xMidYMid meet"/>`}
function boardSvg(){
 const b=state.board,cells=b.cells,W=1100,H=760,sx=110,sy=96,tx=x=>W/2+x*sx,ty=y=>H/2+y*sy;
 let out=`<svg class="boardSvg" viewBox="0 0 ${W} ${H}" preserveAspectRatio="xMidYMid meet" aria-label="Tablero CATAN GG"><defs><filter id="shadow"><feDropShadow dx="0" dy="7" stdDeviation="5" flood-opacity=".35"/></filter><pattern id="foam" width="180" height="100" patternUnits="userSpaceOnUse"><path d="M-10 45q30-22 60 0t60 0t60 0" fill="none" stroke="#fff0ad" stroke-width="7" opacity=".35"/></pattern></defs><rect width="1100" height="760" rx="48" fill="#c88420"/><image href="assets/terrain/sea.svg" x="0" y="0" width="1100" height="760" preserveAspectRatio="xMidYMid slice" opacity=".96"/><rect x="0" y="0" width="1100" height="760" rx="48" fill="url(#foam)"/>`;
 // floating objects in the beer sea
 const floats=[[100,100,48],[980,120,52],[75,610,54],[1010,590,48],[190,700,40],[900,690,44],[520,72,42],[580,700,45]];
 floats.forEach(([x,y,r],i)=>{const kind=i%5; if(kind===0)out+=`<g class="floaty" style="animation-delay:${i*.35}s"><ellipse cx="${x}" cy="${y}" rx="${r}" ry="${r*.42}" fill="#8b4f2d"/><circle cx="${x-r*.35}" cy="${y-5}" r="${r*.18}" fill="#f0c967"/><circle cx="${x+r*.1}" cy="${y-7}" r="${r*.18}" fill="#f0c967"/><circle cx="${x+r*.45}" cy="${y-3}" r="${r*.18}" fill="#f0c967"/></g>`; else if(kind===1)out+=`<g class="floaty" style="animation-delay:${i*.35}s"><ellipse cx="${x}" cy="${y}" rx="${r*.75}" ry="${r*.45}" fill="#7d4a26" stroke="#f0d178" stroke-width="5"/><path d="M${x-r*.55} ${y}h${r*1.1}" stroke="#f0d178" stroke-width="4"/></g>`; else if(kind===2)out+=`<g class="floaty" style="animation-delay:${i*.35}s"><circle cx="${x}" cy="${y}" r="${r*.55}" fill="#e6c77b" stroke="#6c5236" stroke-width="6"/><path d="M${x} ${y-r*.5}v${r}M${x-r*.5} ${y}h${r}" stroke="#6c5236" stroke-width="5"/></g>`; else if(kind===3)out+=`<g class="floaty" style="animation-delay:${i*.35}s"><ellipse cx="${x}" cy="${y}" rx="${r*.7}" ry="${r*.42}" fill="#cbd5d5" stroke="#66777a" stroke-width="5"/><ellipse cx="${x}" cy="${y-2}" rx="${r*.4}" ry="${r*.18}" fill="#8fc2ca"/></g>`; else out+=`<g class="floaty" style="animation-delay:${i*.35}s"><path d="M${x-8} ${y-r*.55}h16v${r*1.1}H${x-8}zM${x-r*.35} ${y-r*.15}h${r*.7}v12h-${r*.7}z" fill="#8d633d" stroke="#4b301e" stroke-width="5"/></g>`});
 const terrainStroke='#3e2d1d';
 cells.forEach(c=>{const x=tx(c.cx),y=ty(c.cy),pts=[];for(let i=0;i<6;i++){const a=Math.PI/180*(60*i-30);pts.push(`${x+sx*.96*Math.cos(a)},${y+sy*.96*Math.sin(a)}`)}out+=`<g class="hex" onclick="hexClick(${c.id})"><polygon points="${pts.join(' ')}" fill="#e7c46b" stroke="${terrainStroke}" stroke-width="5" filter="url(#shadow)"/><image href="${terrainImage(c.terrain)}" x="${x-sx*.92}" y="${y-sy*.92}" width="${sx*1.84}" height="${sy*1.84}" preserveAspectRatio="xMidYMid slice" clip-path="url(#clip${c.id})"/><defs><clipPath id="clip${c.id}"><polygon points="${pts.join(' ')}"/></clipPath></defs>${c.number?`<circle class="numberToken ${[6,8].includes(c.number)?'hot':''}" cx="${x}" cy="${y-28}" r="22"/><text x="${x}" y="${y-21}" text-anchor="middle" font-weight="900" font-size="20" class="num">${c.number}</text>`:''}${state.robber===c.id?`<image href="assets/pieces/cristo.svg" x="${x-25}" y="${y+20}" width="50" height="50"/>`:''}</g>`});
 b.edges.forEach(e=>{const a=b.vertices[e.a],c=b.vertices[e.b],own=ownerOfEdge(e.id),legal=legalEdge(e.id),mx=(tx(a.x)+tx(c.x))/2,my=(ty(a.y)+ty(c.y))/2;out+=`<line class="edge ${own?'owned':''} ${legal?'legalEdge':''}" x1="${tx(a.x)}" y1="${ty(a.y)}" x2="${tx(c.x)}" y2="${ty(c.y)}" stroke="${own?playerColor(own):legal?'#ffe28a':'#59442d'}" stroke-width="${own?14:legal?11:5}" stroke-linecap="round" onclick="edgeClick(${e.id},event)"/>`;if(own){const pp=playerByProfile(own);out+=imgPiece(PIECES[own][0],mx,my,46,46,'roadPiece')}if(legal)out+=`<circle class="edgeTarget" cx="${mx}" cy="${my}" r="7"/>`});
 b.vertices.forEach(v=>{const o=v.owner,legal=legalVertex(v.id,buildMode);out+=`<g class="vertex ${o?'occupied':''} ${legal?'legalVertex':''}" onclick="vertexClick(${v.id},event)"><circle cx="${tx(v.x)}" cy="${ty(v.y)}" r="${o?16:legal?13:5}" fill="${o?playerColor(o):legal?'#ffe28a':'#3e2d1d'}" stroke="${legal?'#fff5c4':'#2c2118'}" stroke-width="${legal?4:2}"/>${o?imgPiece(PIECES[o][pPieceIndex(v.id,o)],tx(v.x),ty(v.y)-3,42,42):''}</g>`});
 b.vertices.forEach(v=>{if(v.port){out+=`<g class="port" transform="translate(${tx(v.x)},${ty(v.y)})"><circle r="24" fill="#f9e7a8" stroke="#50351f" stroke-width="5"/><image href="assets/ports/${v.port==='3:1'?'generic':v.port}.svg" x="-20" y="-20" width="40" height="40"/></g>`}});
 out+='</svg>';return out}
function pPieceIndex(v,prof){const p=playerByProfile(prof);return p&&p.citiesOn.includes(v)?2:1}

function playerByProfile(prof){return Object.values(state.players).find(p=>p.profile===prof)}function playerColor(prof){const p=playerByProfile(prof);return getComputedStyle(document.documentElement).getPropertyValue('--'+p?.color)||'#fff'}function ownerOfEdge(eid){const p=Object.values(state.players).find(p=>p.roadsOn.includes(eid));return p?.profile||null}function pieceAt(v,prof){const p=playerByProfile(prof);return p&&p.citiesOn.includes(v)?2:1}
window.hexClick=id=>{if(state.pendingRobber&&state.turn===myId){send({type:'moveRobber',hexId:id});return}};window.edgeClick=(id,e)=>{e.stopPropagation();if(state.turn!==myId)return;if(state.phase==='placement1'||state.phase==='placement2'){send({type:'placeRoad',pos:id});return}if(state.phase==='playing'&&state.rolled&&buildMode==='road'&&legalEdge(id)){send({type:'build',what:'road',pos:id});buildMode=null;}};window.vertexClick=(id,e)=>{e.stopPropagation();if(state.turn!==myId)return;if(state.phase==='placement1'||state.phase==='placement2'){send({type:'placeSettlement',pos:id});return}if(state.phase==='playing'&&state.rolled&&buildMode&&legalVertex(id,buildMode)){send({type:'build',what:buildMode,pos:id});buildMode=null;}};
function resourcePanel(p){return `<div class="resources">${R.map(r=>`<div class="resource"><img src="${ICON[r]}"><div><b>${p.res[r]}</b><small>${LABEL[r]}</small></div></div>`).join('')}</div>`}
window.setBuildMode=m=>{buildMode=(buildMode===m?null:m);render()};
function actionBar(p){const turn=state.turn===myId&&state.phase==='playing';return `<div class="actionBar"><button class="primary" ${!turn||state.rolled?'disabled':''} onclick="roll()">Tirar dados</button><button ${!turn||!state.rolled?'disabled':''} onclick="setBuildMode('road')">Construir carretera</button><button ${!turn||!state.rolled?'disabled':''} onclick="setBuildMode('settlement')">Construir pueblo</button><button ${!turn||!state.rolled?'disabled':''} onclick="setBuildMode('city')">Construir ciudad</button><button ${!turn||!state.rolled?'disabled':''} onclick="buyDev()">Comprar desarrollo</button><button ${!turn||!state.rolled?'disabled':''} onclick="tradeUI()">Comerciar</button><button ${!turn||!state.rolled?'disabled':''} onclick="bankUI()">Banco</button><button ${!turn?'disabled':''} onclick="endTurn()">Fin de turno</button></div>`}
function devCards(p){return `<div class="devGrid">${p.dev.map((d,i)=>`<button class="devCard" onclick="playDev('${d}')"><img src="${DEV[d][1]}"><span>${DEV[d][0]}</span></button>`).join('')||'<small>No tienes cartas de desarrollo.</small>'}</div>`}
function game(){const p=state.players[myId];const pending=state.pendingTrade&&state.pendingTrade.to===myId;const turnName=state.phase.startsWith('placement')?`Colocación: ${state.players[state.turn]?.name}`:state.turn===myId?'TU TURNO':`Turno de ${state.players[state.turn]?.name||'—'}`;app.innerHTML=`<div class="game"><header><div class="logo mini">CATAN <span>GG</span></div><div class="turn ${state.turn===myId?'mine':''}">${turnName}${state.rolled?' · Puedes actuar':' · Tira los dados'}</div><div class="roomCode">${state.code}</div><button class="ghost smallBtn" onclick="toggleSound()">${localStorage.getItem('catan_sound')==='off'?'🔇':'🔊'}</button><button class="ghost smallBtn" onclick="editConnectedProfile()">Perfil</button><button class="ghost smallBtn" onclick="leaveConfirm()">Salir</button></header><section class="boardArea"><div class="beerLabel">MAR DE CERVEZA · flotadores en el agua</div>${boardSvg()}</section><aside class="sidebar"><div class="you"><div class="youAvatar">${p.photo?`<img src="${p.photo}">`:'🙂'}</div><div><b>${esc(p.name)}</b><small>${p.profile}</small></div><div class="vp">⭐ ${p.vp}</div></div><div class="stats"><span>Carreteras: ${p.roads}</span><span>Pueblos: ${p.settlements}</span><span>Ciudades: ${p.cities}</span><span>Caballeros: ${p.knights}</span></div>${resourcePanel(p)}<h3>Desarrollo</h3>${devCards(p)}<h3>Jugadoras</h3><div class="opponents">${Object.entries(state.players).map(([id,q])=>`<div class="opp"><i class="dot ${q.color}"></i><span>${esc(q.name)}</span><b>⭐ ${q.vp}</b>${state.longestRoad===id?' · Camino más largo':''}${state.largestArmy===id?' · Mayor ejército':''}${q.connected?'':'⚪'}</div>`).join('')}</div><h3>Registro</h3><div class="log">${state.log.slice().reverse().map(x=>`<div>${esc(x)}</div>`).join('')}</div></aside><div class="bottom">${state.phase==='playing'?actionBar(p):`<div class="placementHelp">${state.phase.startsWith('placement')?`${state.phase==='placement1'?'PRIMERA COLOCACIÓN: selecciona un vértice iluminado para tu pueblo y después una arista iluminada para tu carretera.':'SEGUNDA COLOCACIÓN: selecciona un vértice iluminado para tu pueblo y después una arista iluminada para tu carretera.'}`:''}</div>`}</div>${pending?tradeModal(state.pendingTrade):''}${state.pendingRobber&&state.turn===myId?robberModal(state.pendingRobber):''}</div>`}
function robberModal(r){if(r.targets?.length){return `<div class="modal"><div class="modalBox"><h2>Elige a quién robar</h2><p>Cristo está colocado. Selecciona una jugadora con una construcción junto al hexágono.</p><div class="actions">${r.targets.map(id=>`<button onclick="steal('${id}')">${esc(state.players[id].name)}</button>`).join('')}</div></div></div>`}return `<div class="modal"><div class="modalBox"><h2>Ha salido 7</h2><p>Haz clic en cualquier hexágono del tablero para mover a Cristo.</p></div></div>`}window.steal=id=>send({type:'steal',target:id});
function tradeModal(t){const from=state.players[t.from];return `<div class="modal"><div class="modalBox"><h2>Propuesta de comercio</h2><p><b>${esc(from.name)}</b> ofrece <strong>${t.giveN} ${LABEL[t.give]}</strong> a cambio de <strong>${t.takeN} ${LABEL[t.take]}</strong>.</p><div class="actions"><button onclick="respondTrade(true)">Aceptar</button><button class="ghost" onclick="respondTrade(false)">Rechazar</button></div></div></div>`}
window.roll=()=>{send({type:'roll'});beep('dice')};window.endTurn=()=>send({type:'end'});window.buyDev=()=>send({type:'buyDev'});
window.tradeUI=()=>{const others=Object.entries(state.players).filter(([id,p])=>id!==myId&&p.connected);if(!others.length)return toast('No hay otra jugadora conectada.');const html=`<div class="modal"><div class="modalBox"><h2>Comercio</h2><label>Con<select id="tradeTo">${others.map(([id,p])=>`<option value="${id}">${esc(p.name)}</option>`).join('')}</select></label><div class="tradeRow"><input id="giveN" type="number" min="1" value="1"><select id="giveR">${R.map(r=>`<option value="${r}">${LABEL[r]}</option>`).join('')}</select><span>por</span><input id="takeN" type="number" min="1" value="1"><select id="takeR">${R.map(r=>`<option value="${r}">${LABEL[r]}</option>`).join('')}</select></div><div class="actions"><button onclick="sendTrade()">Proponer</button><button class="ghost" onclick="closeModal()">Cancelar</button></div></div></div>`;document.body.insertAdjacentHTML('beforeend',html)};
window.sendTrade=()=>{send({type:'tradeOffer',to:document.getElementById('tradeTo').value,give:document.getElementById('giveR').value,giveN:+document.getElementById('giveN').value,take:document.getElementById('takeR').value,takeN:+document.getElementById('takeN').value});closeModal()};window.respondTrade=a=>{send({type:'tradeRespond',accept:a});closeModal()};window.closeModal=()=>document.querySelector('.modal')?.remove();
window.bankUI=()=>{document.body.insertAdjacentHTML('beforeend',`<div class="modal"><div class="modalBox"><h2>Comercio con banco/puerto</h2><p>El sistema aplicará automáticamente tu mejor ratio disponible: 2:1 de puerto específico, 3:1 genérico o 4:1.</p><div class="tradeRow"><select id="bankGive">${R.map(r=>`<option value="${r}">${LABEL[r]}</option>`).join('')}</select><span>por 1</span><select id="bankTake">${R.map(r=>`<option value="${r}">${LABEL[r]}</option>`).join('')}</select></div><div class="actions"><button onclick="sendBank()">Cambiar</button><button class="ghost" onclick="closeModal()">Cancelar</button></div></div></div>`)};window.sendBank=()=>{send({type:'bankTrade',give:document.getElementById('bankGive').value,take:document.getElementById('bankTake').value});closeModal()};
window.playDev=d=>{if(d==='punto'){send({type:'playDev',card:d});return}if(d==='caballero'){send({type:'playDev',card:d});return}if(d==='monopolio'){document.body.insertAdjacentHTML('beforeend',simpleModal('Aquí mando yo','Elige el recurso',R,'resource'));return}if(d==='abundancia'){document.body.insertAdjacentHTML('beforeend',simpleTwoModal());return}if(d==='construccion'){send({type:'playDev',card:d});toast('Ahora puedes colocar tus dos caminos gratis haciendo clic en el tablero.');}};
function simpleModal(title,txt,opts,id){return `<div class="modal"><div class="modalBox"><h2>${title}</h2><p>${txt}</p><select id="${id}">${opts.map(r=>`<option value="${r}">${LABEL[r]}</option>`).join('')}</select><div class="actions"><button onclick="sendDevResource('${id}')">Jugar</button><button class="ghost" onclick="closeModal()">Cancelar</button></div></div></div>`}window.sendDevResource=id=>{send({type:'playDev',card:'monopolio',resource:document.getElementById(id).value});closeModal()};
function simpleTwoModal(){return `<div class="modal"><div class="modalBox"><h2>Dos por el precio de ninguno</h2><div class="tradeRow"><select id="r1">${R.map(r=>`<option value="${r}">${LABEL[r]}</option>`).join('')}</select><select id="r2">${R.map(r=>`<option value="${r}">${LABEL[r]}</option>`).join('')}</select></div><div class="actions"><button onclick="send({type:'playDev',card:'abundancia',r1:document.getElementById('r1').value,r2:document.getElementById('r2').value});closeModal()">Jugar</button><button class="ghost" onclick="closeModal()">Cancelar</button></div></div></div>`}
window.toggleSound=()=>{localStorage.setItem('catan_sound',localStorage.getItem('catan_sound')==='off'?'on':'off');render()};window.leaveConfirm=()=>{if(confirm('¿Salir de la partida? Tu posición quedará bloqueada si la partida ya ha empezado.'))leave()};
function render(){if(!state)return;if(state.phase==='lobby')lobby();else if(state.phase==='ended'){const p=Object.values(state.players).find(x=>x.profile===state.winner);beep('win');app.innerHTML=`<div class="center"><div class="panel victory"><div class="confetti">🎉✨🎊✨🎉</div><div class="logo">CATAN <span>GG</span></div><div class="winnerPieces">${PIECES[p?.profile||'Raquel'].map(x=>`<img src="${x}">`).join('')}</div><h1>${esc(p?.name||state.winner)}</h1><div class="winPhrase">JODEROS, PUTAAS</div><button onclick="location.reload()">Nueva partida</button></div></div>`}else game()}
home();
