const PROFILES=['Raquel','Sara','Carmen Hernandez','Lucía','Carmen gago','Nuria','Rebeca','Marta'];
const COLORS=['rojo','azul','verde','amarillo','morado','rosa','naranja','turquesa'];
const COLOR_LABEL={rojo:'Rojo',azul:'Azul',verde:'Verde',amarillo:'Amarillo',morado:'Morado',rosa:'Rosa',naranja:'Naranja',turquesa:'Turquesa'};
const R=['croquetas','cerveza','chiva','vater','cruz'];
const LABEL={croquetas:'Croquetas',cerveza:'Cerveza',chiva:'Chiva',vater:'Váter',cruz:'Cruz religiosa de madera'};
const RESCLASS={croquetas:'res-croquetas',cerveza:'res-cerveza',chiva:'res-chiva',vater:'res-vater',cruz:'res-cruz'};
const COST={road:{croquetas:1,cerveza:1},settlement:{croquetas:1,cerveza:1,chiva:1,vater:1},city:{vater:2,cruz:3},dev:{chiva:1,vater:1,cruz:1}};
const ICON={croquetas:'assets/cards/croquetas.svg',cerveza:'assets/cards/cerveza.svg',chiva:'assets/cards/chiva.svg',vater:'assets/cards/vater.svg',cruz:'assets/cards/cruz.svg'};
const DEV={caballero:['El perseguidor','assets/cards/caballero.svg'],punto:['Punto secreto','assets/cards/punto.svg'],monopolio:['Aquí mando yo','assets/cards/monopolio.svg'],abundancia:['Dos por el precio de ninguno','assets/cards/abundancia.svg'],construccion:['Obra y gracia','assets/cards/construccion.svg']};
const PIECES={Raquel:['assets/pieces/Raquel/keyboard.svg','assets/pieces/Raquel/padel.svg','assets/pieces/Raquel/igloo.svg'],Sara:['assets/pieces/Sara/pills.svg','assets/pieces/Sara/controller.svg','assets/pieces/Sara/stable.svg'],'Carmen Hernandez':['assets/pieces/Carmen-Hernandez/cigarette.svg','assets/pieces/Carmen-Hernandez/stadium.svg','assets/pieces/Carmen-Hernandez/falla.svg'],Lucía:['assets/pieces/Lucía/trail.svg','assets/pieces/Lucía/tent.svg','assets/pieces/Lucía/hospital.svg'],'Carmen gago':['assets/pieces/Carmen-gago/poop.svg','assets/pieces/Carmen-gago/bridge.svg','assets/pieces/Carmen-gago/metro.svg'],Nuria:['assets/pieces/Nuria/police-baton.svg','assets/pieces/Nuria/station.svg','assets/pieces/Nuria/jail.svg'],Rebeca:['assets/pieces/Rebeca/vape.svg','assets/pieces/Rebeca/cows.svg','assets/pieces/Rebeca/castle.svg'],Marta:['assets/pieces/Marta/sunglasses.svg','assets/pieces/Marta/gate.svg','assets/pieces/Marta/techno.svg']};
const AVATARS={Raquel:'assets/avatars/Raquel.svg',Sara:'assets/avatars/Sara.svg','Carmen Hernandez':'assets/avatars/Carmen-Hernandez.svg','Lucía':'assets/avatars/Lucia.svg','Carmen gago':'assets/avatars/Carmen-gago.svg',Nuria:'assets/avatars/Nuria.svg',Rebeca:'assets/avatars/Rebeca.svg',Marta:'assets/avatars/Marta.svg'};
const BUILD_PIECES={Raquel:{road:'assets/pieces/raquel_road.svg',settlement:'assets/pieces/raquel_settlement.svg',city:'assets/pieces/raquel_city.svg'},Sara:{road:'assets/pieces/sara_road.svg',settlement:'assets/pieces/sara_settlement.svg',city:'assets/pieces/sara_city.svg'},'Carmen Hernandez':{road:'assets/pieces/carmen_hernandez_road.svg',settlement:'assets/pieces/carmen_hernandez_settlement.svg',city:'assets/pieces/carmen_hernandez_city.svg'},'Lucía':{road:'assets/pieces/lucia_road.svg',settlement:'assets/pieces/lucia_settlement.svg',city:'assets/pieces/lucia_city.svg'},'Carmen gago':{road:'assets/pieces/carmen_gago_road.svg',settlement:'assets/pieces/carmen_gago_settlement.svg',city:'assets/pieces/carmen_gago_city.svg'},Nuria:{road:'assets/pieces/nuria_road.svg',settlement:'assets/pieces/nuria_settlement.svg',city:'assets/pieces/nuria_city.svg'},Rebeca:{road:'assets/pieces/rebeca_road.svg',settlement:'assets/pieces/rebeca_settlement.svg',city:'assets/pieces/rebeca_city.svg'},Marta:{road:'assets/pieces/marta_road.svg',settlement:'assets/pieces/marta_settlement.svg',city:'assets/pieces/marta_city.svg'}};
let ws=null,myId=null,state=null,profile=null; let buildMode=null; let lastDiceKey=''; let gainTimer=null;
const app=document.getElementById('app');
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const send=o=>{if(ws?.readyState===1)ws.send(JSON.stringify(o))};
function avatar(profile,cls='avatarImg'){return `<img class="${cls}" src="${AVATARS[profile]||AVATARS.Raquel}" alt="Avatar de ${esc(profile)}">`}
function toast(t){const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.append(e);setTimeout(()=>e.remove(),2300)}
function beep(type='ok'){if(localStorage.getItem('catan_sound')==='off')return;try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.type='sine';o.frequency.value=type==='dice'?360:type==='win'?720:520;g.gain.value=.045;o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+(type==='win'?.45:.12));}catch{}}
function connect(action){if(ws){try{ws.close()}catch{}}ws=new WebSocket(location.origin.replace(/^http/,'ws'));ws.onopen=()=>send(action);ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='hello'){myId=m.id;localStorage.setItem('catan_lastCode',m.code);if(m.reconnected)toast('Has vuelto a tu partida.');}else if(m.type==='state'){state=m.state;render();if(state.lastGains?.length){clearTimeout(gainTimer);gainTimer=setTimeout(()=>{if(state){state={...state,lastGains:[]};render()}},3200)}if(state.turn===myId&&state.phase==='playing'&&!state.rolled)beep('ok')}else if(m.type==='err'){toast(m.msg);beep('bad')}};ws.onclose=()=>{if(state)toast('Conexión perdida. La partida sigue en memoria mientras el servidor esté activo.')}}
function colorOptions(selected='',occupied=[]){return COLORS.map(c=>`<option value="${c}" ${selected===c?'selected':''} ${occupied.includes(c)?'disabled':''}>${COLOR_LABEL[c]}${occupied.includes(c)?' — ocupado':''}</option>`).join('')}
async function refreshJoinColors(){const code=document.getElementById('code')?.value.trim().toUpperCase();const select=document.getElementById('color');if(!select||!code)return;try{const r=await fetch('/api/rooms/'+encodeURIComponent(code)+'/colors');if(!r.ok)return;const j=await r.json();const current=select.value;const occupied=(j.players||[]).filter(x=>x.profile!==profile).map(x=>x.color);select.innerHTML=colorOptions(current,occupied);if(select.options[select.selectedIndex]?.disabled){const free=[...select.options].find(o=>!o.disabled);if(free)select.value=free.value;}}catch{}}
async function home(){app.innerHTML=`<div class="home"><div class="hero"><div class="logo">CATAN <span>GG</span></div><p>Tu Catan absurdo, personalizado y privado.</p></div><div class="profileGrid">${PROFILES.map(p=>`<button class="profileCard" onclick="choose('${p}')">${avatar(p,'profileAvatar')}<b>${esc(p)}</b><small>Elegir perfil</small></button>`).join('')}</div><div class="tiny">8 perfiles fijos · el color se elige en cada partida · la partida no se guarda</div></div>`}
window.choose=p=>{profile=p;app.innerHTML=`<div class="center"><div class="panel narrow profileChoose"><div class="avatarHero">${avatar(p,'profilePortrait')}</div><h1>${esc(p)}</h1><p class="profileDescription">Perfil fijo. Solo puedes elegir el color de esta partida.</p><label>Color de juego<select id="color">${colorOptions('rojo')}</select></label><div class="actions"><button onclick="createRoom()">Crear partida</button><button onclick="joinScreen()">Unirse a partida</button><button class="ghost" onclick="home()">Volver</button></div></div></div>`};
window.createRoom=()=>{const color=document.getElementById('color').value;connect({type:'create',profile,color})};
window.joinScreen=()=>{app.innerHTML=`<div class="center"><div class="panel narrow profileChoose"><div class="avatarHero">${avatar(profile,'profilePortrait')}</div><h1>${esc(profile)}</h1><label>Código de partida<input id="code" maxlength="5" value="${esc(localStorage.getItem('catan_lastCode')||'')}" style="text-transform:uppercase" oninput="refreshJoinColors()" onblur="refreshJoinColors()"></label><label>Color de juego<select id="color">${colorOptions('rojo')}</select></label><div class="actions"><button onclick="joinRoom()">Entrar</button><button class="ghost" onclick="choose(profile)">Volver</button></div><p class="tiny">Los colores ocupados aparecen deshabilitados.</p></div></div>`;refreshJoinColors()};
window.joinRoom=()=>{const code=document.getElementById('code').value.trim().toUpperCase();if(!code)return toast('Introduce el código de partida.');connect({type:'join',code,profile,color:document.getElementById('color').value})};
function lobby(){const ps=Object.entries(state.players);const occupied=ps.filter(([,p])=>p.connected).map(([,p])=>p.color);app.innerHTML=`<div class="center"><div class="panel lobby"><div class="logo smallLogo">CATAN <span>GG</span></div><h2>Sala <code>${state.code}</code></h2><p>Comparte este código con tus amigas.</p><div class="lobbyPlayers">${ps.map(([id,p])=>`<div class="lobbyP">${avatar(p.profile,'avatar')}<div><b>${esc(p.name)}</b><small>${p.profile}</small></div><i class="dot ${p.color}"></i>${id===state.host?'<span>👑</span>':''}${p.connected?'':'<span class="rejoinTag">LISTA PARA VOLVER</span>'}</div>`).join('')}</div><div class="lobbyFoot"><b>${ps.filter(([,p])=>p.connected).length}/8 conectadas</b>${state.host===myId?`<button onclick="startGame()" ${ps.filter(([,p])=>p.connected).length<2?'disabled':''}>Empezar partida</button>`:'<span>La anfitriona inicia cuando estéis listas.</span>'}<button class="ghost" onclick="leave()">Salir</button></div><div class="colorLegend">${COLORS.map(c=>`<span class="colorChoice ${occupied.includes(c)?'taken':''}"><i class="dot ${c}"></i>${COLOR_LABEL[c]}</span>`).join('')}</div></div></div>`}
window.startGame=()=>send({type:'start'});window.leave=()=>{send({type:'leave'});setTimeout(()=>{state=null;profile=null;home()},100)};
function legalEdge(eid){
 const b=state.board,p=state.players[myId],e=b.edges[eid]; if(!e||p.roadsOn.includes(eid)) return false;
 if(p.roads<=0 && !(p.freeRoads>0)) return false;
 if(!(p.freeRoads>0) && !canPayClient(COST.road)) return false;
 if(state.phase==='placement1'||state.phase==='placement2'){const last=p.settlementsOn[p.settlementsOn.length-1];return last!=null&&(e.a===last||e.b===last);}
 if(buildMode!=='road') return false;
 if(!(p.freeRoads>0) && !canPayClient({croquetas:1,cerveza:1})) return false;
 for(const v of [e.a,e.b]){
   const vv=b.vertices[v]; if(vv.owner===p.profile) return true;
   if(vv.owner) continue;
   if(p.roadsOn.some(x=>{const re=b.edges[x];return re.a===v||re.b===v})) return true;
 }
 return false;
}
function legalVertex(vid,kind){
 const b=state.board,p=state.players[myId],v=b.vertices[vid]; if(!v) return false;
 if(state.phase==='placement1'||state.phase==='placement2'){if(v.owner||v.adj.some(n=>b.vertices[n].owner))return false;return true;}
 if(kind==='city') return p.cities>0 && p.settlementsOn.includes(vid) && canPayClient(COST.city);
 if(kind!=='settlement') return false;
 if(p.settlements<=0 || !canPayClient(COST.settlement)) return false;
 if(v.owner) return false;
 if(v.adj.some(n=>b.vertices[n].owner)) return false;
 return v.adj.some(n=>p.roadsOn.some(eid=>{const e=b.edges[eid];return e.a===n||e.b===n}));
}
function canPayClient(c){const p=state.players[myId];return Object.entries(c).every(([r,n])=>p.res[r]>=n)}
function terrainImage(t){return t==='desierto'?'assets/terrain/desierto.svg':`assets/terrain/${t}.svg`}
function imgPiece(src,x,y,w,h,cls=''){return `<image class="pieceImg ${cls}" href="${src}" x="${x-w/2}" y="${y-h/2}" width="${w}" height="${h}" preserveAspectRatio="xMidYMid meet"/>`}
function boardSvg(){
 const b=state.board,cells=b.cells,W=1100,H=760,sx=112,sy=96,tx=x=>W/2+x*sx,ty=y=>H/2+y*sy;
 const ptsFor=(c)=>{const x=tx(c.cx),y=ty(c.cy),pts=[];for(let i=0;i<6;i++){const a=Math.PI/180*(60*i-30);pts.push({x:x+sx*.96*Math.cos(a),y:y+sy*.96*Math.sin(a)})}return pts};
 const all=cells.flatMap(ptsFor), cross=(o,a,b)=>((a.x-o.x)*(b.y-o.y)-(a.y-o.y)*(b.x-o.x));
 const sorted=all.slice().sort((a,b)=>a.x-b.x||a.y-b.y), lower=[];for(const p of sorted){while(lower.length>=2&&cross(lower[lower.length-2],lower[lower.length-1],p)<=0)lower.pop();lower.push(p)}
 const upper=[];for(const p of sorted.slice().reverse()){while(upper.length>=2&&cross(upper[upper.length-2],upper[upper.length-1],p)<=0)upper.pop();upper.push(p)}
 const hull=lower.slice(0,-1).concat(upper.slice(0,-1)); const islandPath=hull.map((p,i)=>(i?'L':'M')+p.x+' '+p.y).join(' ')+' Z';
 let out=`<svg class="boardSvg" viewBox="0 0 ${W} ${H}" preserveAspectRatio="xMidYMid meet" aria-label="Tablero CATAN GG"><defs>
 <filter id="shadow"><feDropShadow dx="0" dy="7" stdDeviation="5" flood-opacity=".35"/></filter>
 <filter id="islandShadow"><feDropShadow dx="0" dy="12" stdDeviation="10" flood-opacity=".32"/></filter>
 <pattern id="foam" width="170" height="90" patternUnits="userSpaceOnUse"><path d="M-10 44q28-22 56 0t56 0t56 0" fill="none" stroke="#fff7d4" stroke-width="8" stroke-linecap="round" opacity=".32"/><circle cx="34" cy="18" r="4" fill="#fff9dc" opacity=".5"/><circle cx="120" cy="67" r="5" fill="#fff9dc" opacity=".4"/></pattern>
 </defs><rect width="1100" height="760" rx="48" fill="#1c6f8e"/><image href="assets/terrain/sea.svg" x="0" y="0" width="1100" height="760" preserveAspectRatio="xMidYMid slice"/><rect width="1100" height="760" rx="48" fill="url(#foam)"/>
 <path d="${islandPath}" fill="#e3b95c" stroke="#f4df9d" stroke-width="22" stroke-linejoin="round" filter="url(#islandShadow)" opacity=".98"/>`;
 const terrainStroke='#3e2d1d';
 cells.forEach(c=>{const x=tx(c.cx),y=ty(c.cy),pts=[];for(let i=0;i<6;i++){const a=Math.PI/180*(60*i-30);pts.push(`${x+sx*.96*Math.cos(a)},${y+sy*.96*Math.sin(a)}`)}out+=`<g class="hex" onclick="hexClick(${c.id})"><polygon points="${pts.join(' ')}" fill="#e7c46b" stroke="${terrainStroke}" stroke-width="5" filter="url(#shadow)"/><image href="${terrainImage(c.terrain)}" x="${x-sx*.92}" y="${y-sy*.92}" width="${sx*1.84}" height="${sy*1.84}" preserveAspectRatio="xMidYMid slice" clip-path="url(#clip${c.id})"/><defs><clipPath id="clip${c.id}"><polygon points="${pts.join(' ')}"/></clipPath></defs>${c.number?`<circle class="numberToken ${[6,8].includes(c.number)?'hot':''}" cx="${x}" cy="${y-28}" r="22"/><text x="${x}" y="${y-21}" text-anchor="middle" font-weight="900" font-size="20" class="num">${c.number}</text>`:''}${state.robber===c.id?`<image href="assets/pieces/cristo.svg" x="${x-27}" y="${y+18}" width="54" height="54"/>`:''}</g>`});
 b.edges.forEach(e=>{const a=b.vertices[e.a],c=b.vertices[e.b],own=ownerOfEdge(e.id),legal=legalEdge(e.id),mx=(tx(a.x)+tx(c.x))/2,my=(ty(a.y)+ty(c.y))/2;out+=`<line class="edge ${own?'owned':''} ${legal?'legalEdge':''}" x1="${tx(a.x)}" y1="${ty(a.y)}" x2="${tx(c.x)}" y2="${ty(c.y)}" stroke="${own?playerColor(own):legal?'#ffe28a':'#59442d'}" stroke-width="${own?14:legal?11:5}" stroke-linecap="round" onclick="edgeClick(${e.id},event)"/>`;if(own){out+=imgPiece(BUILD_PIECES[own].road,mx,my,46,46,'roadPiece')}if(legal)out+=`<circle class="edgeTarget" cx="${mx}" cy="${my}" r="7"/>`});
 b.vertices.forEach(v=>{const o=v.owner,legal=legalVertex(v.id,buildMode);out+=`<g class="vertex ${o?'occupied':''} ${legal?'legalVertex':''}" onclick="vertexClick(${v.id},event)"><circle cx="${tx(v.x)}" cy="${ty(v.y)}" r="${o?16:legal?13:5}" fill="${o?playerColor(o):legal?'#ffe28a':'#3e2d1d'}" stroke="${legal?'#fff5c4':'#2c2118'}" stroke-width="${legal?4:2}"/>${o?imgPiece(BUILD_PIECES[o][pieceAt(v.id,o)===2?'city':'settlement'],tx(v.x),ty(v.y)-3,42,42):''}</g>`});
 b.vertices.forEach(v=>{if(v.port){out+=`<g class="port" transform="translate(${tx(v.x)},${ty(v.y)})"><circle r="24" fill="#f9e7a8" stroke="#50351f" stroke-width="5"/><image href="assets/ports/${v.port==='3:1'?'generic':v.port}.svg" x="-20" y="-20" width="40" height="40"/></g>`}});
 out+='</svg>';return out}

function pPieceIndex(v,prof){const p=playerByProfile(prof);return p&&p.citiesOn.includes(v)?2:1}

function playerByProfile(prof){return Object.values(state.players).find(p=>p.profile===prof)}function playerColor(prof){const p=playerByProfile(prof);return getComputedStyle(document.documentElement).getPropertyValue('--'+p?.color)||'#fff'}function ownerOfEdge(eid){const p=Object.values(state.players).find(p=>p.roadsOn.includes(eid));return p?.profile||null}function pieceAt(v,prof){const p=playerByProfile(prof);return p&&p.citiesOn.includes(v)?2:1}
window.hexClick=id=>{if(state.pendingRobber&&state.turn===myId){send({type:'moveRobber',hexId:id});return}};window.edgeClick=(id,e)=>{e.stopPropagation();if(state.turn!==myId)return;if(state.phase==='placement1'||state.phase==='placement2'){send({type:'placeRoad',pos:id});return}if(state.phase==='playing'&&state.rolled&&buildMode==='road'&&legalEdge(id)){send({type:'build',what:'road',pos:id});buildMode=null;}};window.vertexClick=(id,e)=>{e.stopPropagation();if(state.turn!==myId)return;if(state.phase==='placement1'||state.phase==='placement2'){send({type:'placeSettlement',pos:id});return}if(state.phase==='playing'&&state.rolled&&buildMode&&legalVertex(id,buildMode)){send({type:'build',what:buildMode,pos:id});buildMode=null;}};
function resourcePanel(p){return `<div class="resources">${R.map(r=>`<div class="resource ${RESCLASS[r]}"><img src="${ICON[r]}"><div><b>${p.res[r]}</b><small>${LABEL[r]}</small></div></div>`).join('')}</div>`}
window.setBuildMode=m=>{buildMode=(buildMode===m?null:m);render()};
function hasLegalRoad(){return state.phase==='playing'&&state.turn===myId&&state.rolled&&state.board.edges.some(e=>legalEdge(e.id));}
function hasLegalSettlement(){return state.phase==='playing'&&state.turn===myId&&state.rolled&&state.board.vertices.some(v=>legalVertex(v.id,'settlement'));}
function hasLegalCity(){return state.phase==='playing'&&state.turn===myId&&state.rolled&&state.board.vertices.some(v=>legalVertex(v.id,'city'));}
function hasBankTrade(){if(state.phase!=='playing'||state.turn!==myId||!state.rolled)return false;const p=state.players[myId];return R.some(g=>{if(!p.res[g])return false;let ratio=4;for(const v of state.board.vertices){if(v.owner===p.profile&&v.port){if(v.port===g)ratio=2;else if(v.port==='3:1')ratio=Math.min(ratio,3)}}return p.res[g]>=ratio&&R.some(t=>t!==g&&state.bank[t]>0)});}
function hasPlayerTrade(){return state.phase==='playing'&&state.turn===myId&&state.rolled&&Object.entries(state.players).some(([id,q])=>id!==myId&&q.connected)&&R.some(r=>state.players[myId].res[r]>0);}
function hasDevPurchase(){const p=state.players[myId];return state.phase==='playing'&&state.turn===myId&&state.rolled&&Object.entries(COST.dev).every(([r,n])=>p.res[r]>=n)&&state.bank.chiva>=0;}
function actionIcon(kind,src,label,extra=''){return `<button class="actionIcon ${extra}" aria-label="${label}" title="${label}" onclick="${kind}"><img src="${src}"><span>${label}</span></button>`}
function actionBar(p){const turn=state.turn===myId&&state.phase==='playing';let h='<div class="actionBar">';if(turn&&!state.rolled)h+='<button class="rollButton" onclick="roll()" aria-label="Tirar dados" title="Tirar dados"><span class="diceGlyph">2</span></button>';if(turn&&state.rolled&&hasLegalRoad())h+=actionIcon("setBuildMode('road')",BUILD_PIECES[p.profile].road,'Carretera',buildMode==='road'?'active':'');if(turn&&state.rolled&&hasLegalSettlement())h+=actionIcon("setBuildMode('settlement')",BUILD_PIECES[p.profile].settlement,'Pueblo',buildMode==='settlement'?'active':'');if(turn&&state.rolled&&hasLegalCity())h+=actionIcon("setBuildMode('city')",BUILD_PIECES[p.profile].city,'Ciudad',buildMode==='city'?'active':'');if(turn&&state.rolled&&hasDevPurchase())h+=actionIcon('buyDev()', 'assets/card-back.svg','Desarrollo');if(turn&&state.rolled&&hasPlayerTrade())h+=actionIcon('tradeUI()','assets/action-trade.svg','Comerciar');if(turn&&state.rolled&&hasBankTrade())h+=actionIcon('bankUI()','assets/action-bank.svg','Banco');if(turn)h+='<button class="endTurn" onclick="endTurn()" aria-label="Fin de turno" title="Fin de turno">✓</button>';h+='</div>';return h}
function devCards(p){return `<div class="devGrid">${p.dev.map((d,i)=>`<button class="devCard" onclick="playDev('${d}')"><img src="${DEV[d][1]}"><span>${DEV[d][0]}</span></button>`).join('')||'<small>No tienes cartas de desarrollo.</small>'}</div>`}
function game(){const p=state.players[myId];const pending=state.pendingTrade&&state.pendingTrade.to===myId;const turnName=state.phase.startsWith('placement')?`Colocación: ${state.players[state.turn]?.name}`:state.turn===myId?'TU TURNO':`Turno de ${state.players[state.turn]?.name||'—'}`;app.innerHTML=`<div class="game"><header><div class="logo mini">CATAN <span>GG</span></div><div class="turn ${state.turn===myId?'mine':''}">${turnName}${state.rolled?' · Puedes actuar':' · Tira los dados'}</div><div class="roomCode">${state.code}</div><button class="ghost smallBtn" onclick="toggleSound()">${localStorage.getItem('catan_sound')==='off'?'SONIDO OFF':'SONIDO ON'}</button><button class="ghost smallBtn" onclick="leaveConfirm()">Salir</button></header><section class="boardArea">${boardSvg()}${diceOverlay()}${gainOverlay()}</section><aside class="sidebar"><div class="you"><div class="youAvatar">${avatar(p.profile,'youAvatarImg')}</div><div><b>${esc(p.name)}</b><small>${p.profile}</small></div><div class="vp">⭐ ${p.vp}</div></div><div class="stats"><span>Carreteras: ${p.roads}</span><span>Pueblos: ${p.settlements}</span><span>Ciudades: ${p.cities}</span><span>Caballeros: ${p.knights}</span></div>${resourcePanel(p)}<h3>Desarrollo</h3>${devCards(p)}<h3>Jugadoras</h3><div class="opponents">${Object.entries(state.players).map(([id,q])=>`<div class="opp">${avatar(q.profile,'oppAvatar')}<span>${esc(q.name)}</span><i class="dot ${q.color}"></i><b>⭐ ${q.vp}</b>${state.longestRoad===id?' · Camino más largo':''}${state.largestArmy===id?' · Mayor ejército':''}${q.connected?'':' · desconectada'}</div>`).join('')}</div><h3>Registro</h3><div class="log">${state.log.slice().reverse().map(x=>`<div>${esc(x)}</div>`).join('')}</div></aside><div class="bottom">${state.phase==='playing'?actionBar(p):`<div class="placementHelp">${state.phase.startsWith('placement')?`${state.phase==='placement1'?'PRIMERA COLOCACIÓN: selecciona un vértice iluminado para tu pueblo y después una arista iluminada para tu carretera.':'SEGUNDA COLOCACIÓN: selecciona un vértice iluminado para tu pueblo y después una arista iluminada para tu carretera.'}`:''}</div>`}</div>${pending?tradeModal(state.pendingTrade):''}${state.pendingRobber&&state.turn===myId?robberModal(state.pendingRobber):''}</div>`}
function diceOverlay(){if(!state.dice)return '';const key=state.dice.join('-');const fresh=key!==lastDiceKey;if(fresh)lastDiceKey=key;return `<div class="diceOverlay ${fresh?'diceFresh':''}" aria-live="polite"><div class="die">${state.dice[0]}</div><span>+</span><div class="die">${state.dice[1]}</div><strong>= ${state.dice[0]+state.dice[1]}</strong></div>`}
function gainOverlay(){const gains=state.lastGains||[];if(!gains.length)return '';return `<div class="gainOverlay" aria-live="polite">${gains.map((g,i)=>`<div class="gainRow" style="--delay:${i*90}ms"><div class="gainWho"><i class="dot ${state.players[g.playerId]?.color||'azul'}"></i><b>${esc(state.players[g.playerId]?.name||g.profile||'Jugadora')}</b></div><div class="gainItems">${Array.from({length:g.amount},()=>`<img src="${ICON[g.resource]}" alt="${LABEL[g.resource]}">`).join('')}</div></div>`).join('')}</div>`}
function robberModal(r){if(r.targets?.length){return `<div class="modal"><div class="modalBox"><h2>Elige a quién robar</h2><p>Cristo está colocado. Selecciona una jugadora con una construcción junto al hexágono.</p><div class="actions">${r.targets.map(id=>`<button onclick="steal('${id}')">${esc(state.players[id].name)}</button>`).join('')}</div></div></div>`}return `<div class="modal"><div class="modalBox"><h2>Ha salido 7</h2><p>Haz clic en cualquier hexágono del tablero para mover a Cristo.</p></div></div>`}window.steal=id=>send({type:'steal',target:id});
function tradeModal(t){const from=state.players[t.from];return `<div class="modal"><div class="modalBox"><h2>Propuesta de comercio</h2><p><b>${esc(from.name)}</b> ofrece <strong>${t.giveN} ${LABEL[t.give]}</strong> a cambio de <strong>${t.takeN} ${LABEL[t.take]}</strong>.</p><div class="actions"><button onclick="respondTrade(true)">Aceptar</button><button class="ghost" onclick="respondTrade(false)">Rechazar</button></div></div></div>`}
window.roll=()=>{send({type:'roll'});beep('dice')};window.endTurn=()=>send({type:'end'});window.buyDev=()=>send({type:'buyDev'});
window.tradeUI=()=>{const others=Object.entries(state.players).filter(([id,p])=>id!==myId&&p.connected);if(!others.length)return toast('No hay otra jugadora conectada.');const html=`<div class="modal"><div class="modalBox"><h2>Comercio</h2><label>Con<select id="tradeTo">${others.map(([id,p])=>`<option value="${id}">${esc(p.name)}</option>`).join('')}</select></label><div class="tradeRow"><input id="giveN" type="number" min="1" value="1"><select id="giveR">${R.map(r=>`<option value="${r}">${LABEL[r]}</option>`).join('')}</select><span>por</span><input id="takeN" type="number" min="1" value="1"><select id="takeR">${R.map(r=>`<option value="${r}">${LABEL[r]}</option>`).join('')}</select></div><div class="actions"><button onclick="sendTrade()">Proponer</button><button class="ghost" onclick="closeModal()">Cancelar</button></div></div></div>`;document.body.insertAdjacentHTML('beforeend',html)};
window.sendTrade=()=>{send({type:'tradeOffer',to:document.getElementById('tradeTo').value,give:document.getElementById('giveR').value,giveN:+document.getElementById('giveN').value,take:document.getElementById('takeR').value,takeN:+document.getElementById('takeN').value});closeModal()};window.respondTrade=a=>{send({type:'tradeRespond',accept:a});closeModal()};window.closeModal=()=>document.querySelector('.modal')?.remove();
window.bankUI=()=>{document.body.insertAdjacentHTML('beforeend',`<div class="modal"><div class="modalBox"><h2>Comercio con banco/puerto</h2><p>El sistema aplicará automáticamente tu mejor ratio disponible: 2:1 de puerto específico, 3:1 genérico o 4:1.</p><div class="tradeRow"><select id="bankGive">${R.map(r=>`<option value="${r}">${LABEL[r]}</option>`).join('')}</select><span>por 1</span><select id="bankTake">${R.map(r=>`<option value="${r}">${LABEL[r]}</option>`).join('')}</select></div><div class="actions"><button onclick="sendBank()">Cambiar</button><button class="ghost" onclick="closeModal()">Cancelar</button></div></div></div>`)};window.sendBank=()=>{send({type:'bankTrade',give:document.getElementById('bankGive').value,take:document.getElementById('bankTake').value});closeModal()};
window.playDev=d=>{if(d==='punto'){send({type:'playDev',card:d});return}if(d==='caballero'){send({type:'playDev',card:d});return}if(d==='monopolio'){document.body.insertAdjacentHTML('beforeend',simpleModal('Aquí mando yo','Elige el recurso',R,'resource'));return}if(d==='abundancia'){document.body.insertAdjacentHTML('beforeend',simpleTwoModal());return}if(d==='construccion'){send({type:'playDev',card:d});toast('Ahora puedes colocar tus dos caminos gratis haciendo clic en el tablero.');}};
function simpleModal(title,txt,opts,id){return `<div class="modal"><div class="modalBox"><h2>${title}</h2><p>${txt}</p><select id="${id}">${opts.map(r=>`<option value="${r}">${LABEL[r]}</option>`).join('')}</select><div class="actions"><button onclick="sendDevResource('${id}')">Jugar</button><button class="ghost" onclick="closeModal()">Cancelar</button></div></div></div>`}window.sendDevResource=id=>{send({type:'playDev',card:'monopolio',resource:document.getElementById(id).value});closeModal()};
function simpleTwoModal(){return `<div class="modal"><div class="modalBox"><h2>Dos por el precio de ninguno</h2><div class="tradeRow"><select id="r1">${R.map(r=>`<option value="${r}">${LABEL[r]}</option>`).join('')}</select><select id="r2">${R.map(r=>`<option value="${r}">${LABEL[r]}</option>`).join('')}</select></div><div class="actions"><button onclick="send({type:'playDev',card:'abundancia',r1:document.getElementById('r1').value,r2:document.getElementById('r2').value});closeModal()">Jugar</button><button class="ghost" onclick="closeModal()">Cancelar</button></div></div></div>`}
window.toggleSound=()=>{localStorage.setItem('catan_sound',localStorage.getItem('catan_sound')==='off'?'on':'off');render()};window.leaveConfirm=()=>{if(confirm('¿Salir de la partida? Podrás volver a entrar con el mismo código y perfil mientras la partida siga activa.'))leave()};
function render(){if(!state)return;if(state.phase==='lobby')lobby();else if(state.phase==='ended'){const p=Object.values(state.players).find(x=>x.profile===state.winner);beep('win');app.innerHTML=`<div class="center"><div class="panel victory"><div class="confetti">VICTORIA</div><div class="logo">CATAN <span>GG</span></div><div class="winnerPieces">${PIECES[p?.profile||'Raquel'].map(x=>`<img src="${x}">`).join('')}</div><h1>${esc(p?.name||state.winner)}</h1><div class="winPhrase">JODEROS, PUTAAS</div><button onclick="location.reload()">Nueva partida</button></div></div>`}else game()}
home();
