const PROFILES=['Raquel','Sara','Carmen Hernandez','Lucía','Carmen gago','Nuria','Rebeca','Marta'];
const COLORS=['rojo','azul','verde','amarillo','morado','rosa','naranja','turquesa'];
const R=['croquetas','cerveza','chiva','vater','cruz'];
const LABEL={croquetas:'Croquetas',cerveza:'Cerveza',chiva:'Chiva',vater:'Váter',cruz:'Cruz religiosa de madera'};
const ICON={croquetas:'🍗',cerveza:'🍺',chiva:'🐐',vater:'🚽',cruz:'✝️'};
const DEV={caballero:['El perseguidor','🧍‍♂️🛍️'],punto:['Punto secreto','⭐'],monopolio:['Aquí mando yo','👑'],abundancia:['Dos por el precio de ninguno','🎁🎁'],construccion:['Obra y gracia','🛣️🛣️']};
const PIECES={Raquel:['⌨️','🎾','🧊'],Sara:['💊','🎮','🐴'],'Carmen Hernandez':['🚬','🏟️','🎭'],Lucía:['🥾','⛺','🏥'],'Carmen gago':['💩','🌉','🚇'],Nuria:['🚓','🏢','🔒'],Rebeca:['💨','🐄','🏰'],Marta:['🕶️','🚧','🎧']};
const FACE=['😎','🤪','😂','😈','🤠','🤓','🥳','😏'];
let ws=null,myId=null,state=null,profile=null;
const app=document.getElementById('app');
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const send=o=>{if(ws?.readyState===1)ws.send(JSON.stringify(o))};
function toast(t){const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.append(e);setTimeout(()=>e.remove(),2300)}
function beep(type='ok'){if(localStorage.getItem('catan_sound')==='off')return;try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.type='sine';o.frequency.value=type==='dice'?360:type==='win'?720:520;g.gain.value=.045;o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+(type==='win'?.45:.12));}catch{}}
function connect(action){if(ws){try{ws.close()}catch{}}ws=new WebSocket(location.origin.replace(/^http/,'ws'));ws.onopen=()=>send(action);ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='hello'){myId=m.id;localStorage.setItem('catan_lastCode',m.code)}else if(m.type==='state'){state=m.state;render(); if(state.turn===myId&&state.phase==='playing'&&!state.rolled)beep('ok')}else if(m.type==='err'){toast(m.msg);beep('bad')}};ws.onclose=()=>toast('Conexión perdida. Si vuelves a abrir la misma partida, el estado del servidor se conserva mientras siga activa.')}
function saved(p){try{return JSON.parse(localStorage.getItem('catan_profile_'+p)||'{}')}catch{return{}}}
function home(){app.innerHTML=`<div class="home"><div class="hero"><div class="logo">CATAN <span>GG</span></div><p>Tu Catan absurdo, personalizado y privado.</p></div><div class="profileGrid">${PROFILES.map((p,i)=>{const s=saved(p);return `<button class="profileCard" onclick="choose('${p}')"><div class="face">${s.photo?`<img src="${esc(s.photo)}">`:FACE[i]}</div><b>${esc(s.name||p)}</b><small>${p}</small></button>`}).join('')}</div><div class="tiny">2–8 jugadoras · sin cuentas · sin chat integrado · solo efectos de juego</div></div>`}
window.choose=p=>{profile=p;const s=saved(p);app.innerHTML=`<div class="center"><div class="panel narrow"><h1>${esc(p)}</h1><div class="avatarEdit">${s.photo?`<img id="preview" src="${esc(s.photo)}">`:`<div id="preview" class="face big">${FACE[PROFILES.indexOf(p)]}</div>`}<label class="upload">Cambiar foto<input id="photo" type="file" accept="image/*" onchange="photoPreview(event)"></label></div><label>Nombre<input id="name" maxlength="24" value="${esc(s.name||p)}"></label><label>Color<select id="color">${COLORS.map(c=>`<option ${s.color===c?'selected':''}>${c}</option>`).join('')}</select></label><div class="actions"><button onclick="createRoom()">Crear partida</button><button onclick="joinScreen()">Unirse a partida</button><button class="ghost" onclick="home()">Volver</button></div></div></div>`};
window.photoPreview=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{document.getElementById('preview').outerHTML=`<img id="preview" class="face big" src="${r.result}">`;window._photo=r.result};r.readAsDataURL(f)};
function saveProfile(){const o={name:document.getElementById('name').value.trim()||profile,color:document.getElementById('color').value,photo:window._photo||saved(profile).photo||''};localStorage.setItem('catan_profile_'+profile,JSON.stringify(o));return o}
window.createRoom=()=>{const s=saveProfile();connect({type:'create',profile,name:s.name,color:s.color,photo:s.photo})};
window.joinScreen=()=>{const s=saved(profile);app.innerHTML=`<div class="center"><div class="panel narrow"><h1>Unirse</h1><label>Código de partida<input id="code" maxlength="5" value="${esc(localStorage.getItem('catan_lastCode')||'')}" style="text-transform:uppercase"></label><label>Nombre<input id="name" maxlength="24" value="${esc(s.name||profile)}"></label><label>Color<select id="color">${COLORS.map(c=>`<option ${s.color===c?'selected':''}>${c}</option>`).join('')}</select></label><div class="actions"><button onclick="joinRoom()">Entrar</button><button class="ghost" onclick="choose(profile)">Volver</button></div></div></div>`};
window.joinRoom=()=>{const s={name:document.getElementById('name').value.trim()||profile,color:document.getElementById('color').value,photo:saved(profile).photo||''};localStorage.setItem('catan_profile_'+profile,JSON.stringify(s));connect({type:'join',code:document.getElementById('code').value.toUpperCase(),profile,name:s.name,color:s.color,photo:s.photo})};
function lobby(){const ps=Object.entries(state.players);app.innerHTML=`<div class="center"><div class="panel lobby"><div class="logo smallLogo">CATAN <span>GG</span></div><h2>Sala <code>${state.code}</code></h2><p>Comparte este código con tus amigas.</p><div class="lobbyPlayers">${ps.map(([id,p])=>`<div class="lobbyP"><div class="avatar">${p.photo?`<img src="${p.photo}">`:'🙂'}</div><div><b>${esc(p.name)}</b><small>${p.profile}</small></div><i class="dot ${p.color}"></i>${id===state.host?'<span>👑</span>':''}${p.connected?'':'<span>⚪</span>'}</div>`).join('')}</div><div class="lobbyFoot"><b>${ps.filter(([,p])=>p.connected).length}/8 conectadas</b>${state.host===myId?`<button onclick="startGame()" ${ps.filter(([,p])=>p.connected).length<2?'disabled':''}>Empezar partida</button>`:'<span>La anfitriona inicia cuando estéis listas.</span>'}<button class="ghost" onclick="leave()">Salir</button></div></div></div>`}
window.startGame=()=>send({type:'start'});window.leave=()=>{send({type:'leave'});setTimeout(home,100)};
function boardSvg(){const b=state.board;const cells=b.cells;const minX=Math.min(...b.vertices.map(v=>v.x))-1.5,maxX=Math.max(...b.vertices.map(v=>v.x))+1.5,minY=Math.min(...b.vertices.map(v=>v.y))-1.5,maxY=Math.max(...b.vertices.map(v=>v.y))+1.5;const W=900,H=650,sx=110,sy=95;const tx=x=>W/2+x*sx,ty=y=>H/2+y*sy;let out=`<svg class="boardSvg" viewBox="0 0 ${W} ${H}" preserveAspectRatio="xMidYMid meet">`;
 out+=`<defs><linearGradient id="beer" x2="0" y2="1"><stop stop-color="#f6d77a"/><stop offset=".55" stop-color="#d9a438"/><stop offset="1" stop-color="#b97919"/></linearGradient><filter id="shadow"><feDropShadow dx="0" dy="4" stdDeviation="3" flood-opacity=".35"/></filter></defs>`;
 out+=`<rect width="900" height="650" rx="36" fill="url(#beer)"/><g class="foam">${[...Array(18)].map((_,i)=>`<circle cx="${(i*53)%880+10}" cy="${(i*91)%630+10}" r="${3+(i%5)}"/>`).join('')}</g>`;
 const terrainFill={croquetas:'#b96736',cerveza:'#d7a538',chiva:'#5e8e55',vater:'#8b7a68',cruz:'#756d82',desierto:'#caa66a'};
 cells.forEach(c=>{const x=tx(c.cx),y=ty(c.cy),pts=[];for(let i=0;i<6;i++){const a=Math.PI/180*(60*i-30);pts.push(`${x+sx*.96*Math.cos(a)},${y+sy*.96*Math.sin(a)}`)}const label=c.terrain==='desierto'?'🏜️':ICON[c.terrain];out+=`<g class="hex" data-id="${c.id}" onclick="hexClick(${c.id})"><polygon points="${pts.join(' ')}" fill="${terrainFill[c.terrain]}" filter="url(#shadow)"/><text x="${x}" y="${y+8}" text-anchor="middle" font-size="34">${label}</text>${c.number?`<circle cx="${x}" cy="${y-28}" r="19" fill="#fff8df"/><text x="${x}" y="${y-21}" text-anchor="middle" font-weight="900" font-size="19" class="num ${[6,8].includes(c.number)?'hot':''}">${c.number}</text>`:''}${state.robber===c.id?`<text x="${x}" y="${y+44}" text-anchor="middle" font-size="31">✝️</text>`:''}</g>`});
 // ports
 b.vertices.forEach(v=>{if(v.port){out+=`<g class="port" transform="translate(${tx(v.x)},${ty(v.y)})"><circle r="15"/><text y="6" text-anchor="middle" font-size="15">${v.port==='3:1'?'3:1':ICON[v.port]}</text></g>`}});
 // edges then vertices
 b.edges.forEach(e=>{const a=b.vertices[e.a],c=b.vertices[e.b];const own=ownerOfEdge(e.id);out+=`<line class="edge ${own?'owned':''}" x1="${tx(a.x)}" y1="${ty(a.y)}" x2="${tx(c.x)}" y2="${ty(c.y)}" stroke="${own?playerColor(own):'#5d4734'}" stroke-width="${own?10:7}" stroke-linecap="round" onclick="edgeClick(${e.id},event)"/>`});
 b.vertices.forEach(v=>{const o=v.owner;out+=`<g class="vertex ${o?'occupied':''}" onclick="vertexClick(${v.id},event)"><circle cx="${tx(v.x)}" cy="${ty(v.y)}" r="${o?13:8}" fill="${o?playerColor(o):'#f7e8bf'}" stroke="#3b2b20" stroke-width="3"/>${o?`<text x="${tx(v.x)}" y="${ty(v.y)+6}" text-anchor="middle" font-size="15">${pieceAt(v.id,o)}</text>`:''}</g>`});out+='</svg>';return out}
function playerByProfile(prof){return Object.values(state.players).find(p=>p.profile===prof)}function playerColor(prof){const p=playerByProfile(prof);return getComputedStyle(document.documentElement).getPropertyValue('--'+p?.color)||'#fff'}function ownerOfEdge(eid){const p=Object.values(state.players).find(p=>p.roadsOn.includes(eid));return p?.profile||null}function pieceAt(v,prof){const p=playerByProfile(prof);if(p.citiesOn.includes(v))return PIECES[prof][2];return PIECES[prof][1]}
window.hexClick=id=>{if(state.pendingRobber&&state.turn===myId){send({type:'moveRobber',hexId:id});return}};window.edgeClick=(id,e)=>{e.stopPropagation();if(state.turn!==myId)return; if(state.phase==='placement1'||state.phase==='placement2')send({type:'placeRoad',pos:id});else if(state.phase==='playing'&&state.rolled)send({type:'build',what:'road',pos:id})};window.vertexClick=(id,e)=>{e.stopPropagation();if(state.turn!==myId)return;if(state.phase==='placement1'||state.phase==='placement2')send({type:'placeSettlement',pos:id});else if(state.phase==='playing'&&state.rolled){const p=state.players[myId];if(p.settlementsOn.includes(id))send({type:'build',what:'city',pos:id});else send({type:'build',what:'settlement',pos:id});}};
function resourcePanel(p){return `<div class="resources">${R.map(r=>`<div class="resource"><span>${ICON[r]}</span><div><b>${p.res[r]}</b><small>${LABEL[r]}</small></div></div>`).join('')}</div>`}
function actionBar(p){const turn=state.turn===myId&&state.phase==='playing';return `<div class="actionBar"><button class="primary" ${!turn||state.rolled?'disabled':''} onclick="roll()">🎲 Tirar dados</button><button ${!turn||!state.rolled?'disabled':''} onclick="buyDev()">🃏 Comprar desarrollo</button><button ${!turn||!state.rolled?'disabled':''} onclick="tradeUI()">🤝 Comerciar</button><button ${!turn||!state.rolled?'disabled':''} onclick="bankUI()">🏦 Banco</button><button ${!turn?'disabled':''} onclick="endTurn()">Fin de turno</button></div>`}
function devCards(p){return `<div class="devGrid">${p.dev.map((d,i)=>`<button class="devCard" onclick="playDev('${d}')"><strong>${DEV[d][1]}</strong><span>${DEV[d][0]}</span></button>`).join('')||'<small>No tienes cartas de desarrollo.</small>'}</div>`}
function game(){const p=state.players[myId];const pending=state.pendingTrade&&state.pendingTrade.to===myId;const turnName=state.phase.startsWith('placement')?`Colocación: ${state.players[state.turn]?.name}`:state.turn===myId?'TU TURNO':`Turno de ${state.players[state.turn]?.name||'—'}`;app.innerHTML=`<div class="game"><header><div class="logo mini">CATAN <span>GG</span></div><div class="turn ${state.turn===myId?'mine':''}">${turnName}${state.rolled?' · Puedes actuar':' · Tira los dados'}</div><div class="roomCode">${state.code}</div><button class="ghost smallBtn" onclick="toggleSound()">${localStorage.getItem('catan_sound')==='off'?'🔇':'🔊'}</button><button class="ghost smallBtn" onclick="leaveConfirm()">Salir</button></header><section class="boardArea"><div class="beerLabel">MAR DE CERVEZA · 🌊🍺</div>${boardSvg()}</section><aside class="sidebar"><div class="you"><div class="youAvatar">${p.photo?`<img src="${p.photo}">`:'🙂'}</div><div><b>${esc(p.name)}</b><small>${p.profile}</small></div><div class="vp">⭐ ${p.vp}</div></div><div class="stats"><span>🛣️ ${p.roads}</span><span>🏠 ${p.settlements}</span><span>🏙️ ${p.cities}</span><span>⚔️ ${p.knights}</span></div>${resourcePanel(p)}<h3>Desarrollo</h3>${devCards(p)}<h3>Jugadoras</h3><div class="opponents">${Object.entries(state.players).map(([id,q])=>`<div class="opp"><i class="dot ${q.color}"></i><span>${esc(q.name)}</span><b>⭐ ${q.vp}</b>${state.longestRoad===id?'🛣️':''}${state.largestArmy===id?'⚔️':''}${q.connected?'':'⚪'}</div>`).join('')}</div><h3>Registro</h3><div class="log">${state.log.slice().reverse().map(x=>`<div>${esc(x)}</div>`).join('')}</div></aside><div class="bottom">${state.phase==='playing'?actionBar(p):`<div class="placementHelp">${state.phase.startsWith('placement')?`Coloca ${state.phase==='placement1'?'tu pueblo y después tu camino':'tu segundo pueblo y después tu camino'}. Haz clic en el tablero.`:''}</div>`}</div>${pending?tradeModal(state.pendingTrade):''}${state.pendingRobber&&state.turn===myId?robberModal(state.pendingRobber):''}</div>`}
function robberModal(r){if(r.targets?.length){return `<div class="modal"><div class="modalBox"><h2>Elige a quién robar</h2><p>Cristo está colocado. Selecciona una jugadora con una construcción junto al hexágono.</p><div class="actions">${r.targets.map(id=>`<button onclick="steal('${id}')">${esc(state.players[id].name)}</button>`).join('')}</div></div></div>`}return `<div class="modal"><div class="modalBox"><h2>Ha salido 7</h2><p>Haz clic en cualquier hexágono del tablero para mover a Cristo.</p></div></div>`}window.steal=id=>send({type:'steal',target:id});
function tradeModal(t){const from=state.players[t.from];return `<div class="modal"><div class="modalBox"><h2>Propuesta de comercio</h2><p><b>${esc(from.name)}</b> ofrece <strong>${t.giveN} ${LABEL[t.give]}</strong> a cambio de <strong>${t.takeN} ${LABEL[t.take]}</strong>.</p><div class="actions"><button onclick="respondTrade(true)">Aceptar</button><button class="ghost" onclick="respondTrade(false)">Rechazar</button></div></div></div>`}
window.roll=()=>{send({type:'roll'});beep('dice')};window.endTurn=()=>send({type:'end'});window.buyDev=()=>send({type:'buyDev'});
window.tradeUI=()=>{const others=Object.entries(state.players).filter(([id,p])=>id!==myId&&p.connected);if(!others.length)return toast('No hay otra jugadora conectada.');const html=`<div class="modal"><div class="modalBox"><h2>Comercio</h2><label>Con<select id="tradeTo">${others.map(([id,p])=>`<option value="${id}">${esc(p.name)}</option>`).join('')}</select></label><div class="tradeRow"><input id="giveN" type="number" min="1" value="1"><select id="giveR">${R.map(r=>`<option value="${r}">${LABEL[r]}</option>`).join('')}</select><span>por</span><input id="takeN" type="number" min="1" value="1"><select id="takeR">${R.map(r=>`<option value="${r}">${LABEL[r]}</option>`).join('')}</select></div><div class="actions"><button onclick="sendTrade()">Proponer</button><button class="ghost" onclick="closeModal()">Cancelar</button></div></div></div>`;document.body.insertAdjacentHTML('beforeend',html)};
window.sendTrade=()=>{send({type:'tradeOffer',to:document.getElementById('tradeTo').value,give:document.getElementById('giveR').value,giveN:+document.getElementById('giveN').value,take:document.getElementById('takeR').value,takeN:+document.getElementById('takeN').value});closeModal()};window.respondTrade=a=>{send({type:'tradeRespond',accept:a});closeModal()};window.closeModal=()=>document.querySelector('.modal')?.remove();
window.bankUI=()=>{document.body.insertAdjacentHTML('beforeend',`<div class="modal"><div class="modalBox"><h2>Comercio con banco/puerto</h2><p>El sistema aplicará automáticamente tu mejor ratio disponible: 2:1 de puerto específico, 3:1 genérico o 4:1.</p><div class="tradeRow"><select id="bankGive">${R.map(r=>`<option value="${r}">${LABEL[r]}</option>`).join('')}</select><span>por 1</span><select id="bankTake">${R.map(r=>`<option value="${r}">${LABEL[r]}</option>`).join('')}</select></div><div class="actions"><button onclick="sendBank()">Cambiar</button><button class="ghost" onclick="closeModal()">Cancelar</button></div></div></div>`)};window.sendBank=()=>{send({type:'bankTrade',give:document.getElementById('bankGive').value,take:document.getElementById('bankTake').value});closeModal()};
window.playDev=d=>{if(d==='punto'){send({type:'playDev',card:d});return}if(d==='caballero'){send({type:'playDev',card:d});return}if(d==='monopolio'){document.body.insertAdjacentHTML('beforeend',simpleModal('Aquí mando yo','Elige el recurso',R,'resource'));return}if(d==='abundancia'){document.body.insertAdjacentHTML('beforeend',simpleTwoModal());return}if(d==='construccion'){send({type:'playDev',card:d});toast('Ahora puedes colocar tus dos caminos gratis haciendo clic en el tablero.');}};
function simpleModal(title,txt,opts,id){return `<div class="modal"><div class="modalBox"><h2>${title}</h2><p>${txt}</p><select id="${id}">${opts.map(r=>`<option value="${r}">${LABEL[r]}</option>`).join('')}</select><div class="actions"><button onclick="sendDevResource('${id}')">Jugar</button><button class="ghost" onclick="closeModal()">Cancelar</button></div></div></div>`}window.sendDevResource=id=>{send({type:'playDev',card:'monopolio',resource:document.getElementById(id).value});closeModal()};
function simpleTwoModal(){return `<div class="modal"><div class="modalBox"><h2>Dos por el precio de ninguno</h2><div class="tradeRow"><select id="r1">${R.map(r=>`<option value="${r}">${LABEL[r]}</option>`).join('')}</select><select id="r2">${R.map(r=>`<option value="${r}">${LABEL[r]}</option>`).join('')}</select></div><div class="actions"><button onclick="send({type:'playDev',card:'abundancia',r1:document.getElementById('r1').value,r2:document.getElementById('r2').value});closeModal()">Jugar</button><button class="ghost" onclick="closeModal()">Cancelar</button></div></div></div>`}
window.toggleSound=()=>{localStorage.setItem('catan_sound',localStorage.getItem('catan_sound')==='off'?'on':'off');render()};window.leaveConfirm=()=>{if(confirm('¿Salir de la partida? Tu posición quedará bloqueada si la partida ya ha empezado.'))leave()};
function render(){if(!state)return;if(state.phase==='lobby')lobby();else if(state.phase==='ended'){const p=Object.values(state.players).find(x=>x.profile===state.winner);beep('win');app.innerHTML=`<div class="center"><div class="panel victory"><div class="confetti">🎉✨🎊✨🎉</div><div class="logo">CATAN <span>GG</span></div><div class="winnerPiece">${PIECES[p?.profile||'Raquel'].join(' ')}</div><h1>${esc(p?.name||state.winner)}</h1><div class="winPhrase">JODEROS, PUTAAS</div><button onclick="location.reload()">Nueva partida</button></div></div>`}else game()}
home();
